### ISSUE TITLE
[FIX] Update gems to fix security issues

### ISSUE THREAD

**Issue by denys-medynskyi** [pivorakmeetup/pivorak-web-app#680]
This list of gems should be updated to fix the security issues:

https://github.com/pivorakmeetup/pivorak-web-app/network/alerts

**Comment by aleksacastle** [comment]
I take it

**Comment by aleksacastle** [comment]
Due to an invalid link in the description and lack of information, I've performed analyze of  gems with [hakiri](https://hakiri.io/facets).
Which found 4 vulnerabilities in 251 gems in Gemfile.lock:
[Report link](https://hakiri.io/facets/77b6e713911b83)
Duplicate below in case if link will be impaired.
1) [Vulnerability in nokogiri](https://hakiri.io/technologies/nokogiri/issues/d861245592505c)
2) [Vulnerability in devise](https://hakiri.io/technologies/devise/issues/39cff5dbeb9f62)
3) [Vulnerability in simple_form](https://hakiri.io/technologies/simple_form/issues/59feb4812f9143)

[Pull request: ](https://github.com/pivorakmeetup/pivorak-web-app/pull/834)
