### ISSUE TITLE
[UI] Waiting list notice message rendering 

### ISSUE THREAD

**Issue by yanvit** [pivorakmeetup/pivorak-web-app#779]
Hi, just found a small issue with waiting list link rendering on user's notice message.

Check out the screenshot below

<img width="1299" alt="Screen Shot 2019-05-20 at 15 13 54" src="https://user-images.githubusercontent.com/28675445/58030724-af823d80-7b27-11e9-9939-d45fecf6acf4.png">

**Comment by owaiswiz** [comment]
I'll take this

**Comment by filipewl** [comment]
Hey! 👋 

May I try this one? It looks like to be just an HTML escaping issue.

**Comment by filipewl** [comment]
This seems to have been fixed in https://github.com/pivorakmeetup/pivorak-web-app/commit/02e83a5fb575ad4d23643da330c51d09ac1669f8 already.

Just tested it and here's what I'm getting:

<img width="632" alt="Screen Shot 2019-10-13 at 20 25 26" src="https://user-images.githubusercontent.com/381395/66724077-a60bb180-edf7-11e9-8a16-8e5b60ead5c5.png">

**Comment by yanvit** [comment]
Yeap, the issue seems to be resolved :)
